# Generated by Django 5.0.7 on 2024-08-07 14:36

from django.db import migrations

datetime_stamp_show = '2024-08-27 00:00:01 -0300'
datetime_stamp_print = '2024-08-29 12:00:01 -0300'


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Deadline = apps.get_model("delay", "Deadline")
    db_alias = schema_editor.connection.alias
    Deadline.objects.using(db_alias).bulk_create([
        Deadline(name="show_challenge_explanation", deadline=datetime_stamp_show),
        Deadline(name="start_printing_while_delaying", deadline=datetime_stamp_print),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Deadline instances,
    # so reverse_func() should delete them.
    Deadline = apps.get_model("delay", "Deadline")
    db_alias = schema_editor.connection.alias
    Deadline.objects.using(db_alias).filter(name="show_challenge_explanation").delete()
    Deadline.objects.using(db_alias).filter(name="start_printing_while_delaying").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0003_deadline'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func),
    ]
