# Generated by Django 5.0.7 on 2024-08-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0004_auto_20240807_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sogroup',
            old_name='group_number',
            new_name='repo_name',
        ),
        migrations.AlterField(
            model_name='sogroup',
            name='group_name',
            field=models.CharField(blank=True, help_text='Optional. The name of the group', max_length=100, null=True),
        ),
    ]
