# Generated by Django 5.0.7 on 2024-08-09 00:33

import delay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0006_alter_sogroup_repo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sogroup',
            name='beaten',
        ),
        migrations.RemoveField(
            model_name='sogroup',
            name='beaten_timestamp',
        ),
        migrations.AddField(
            model_name='sogroup',
            name='challenge_won',
            field=models.BooleanField(default=False, editable=False, help_text='True if the group has won the challenge'),
        ),
        migrations.AddField(
            model_name='sogroup',
            name='challenge_won_timestamp',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text="Leave Empty. It'll be filled when the group wins the challenge", null=True),
        ),
        migrations.AlterField(
            model_name='sogroup',
            name='repo_name',
            field=models.CharField(help_text='The repo name must follow the pattern soYYYYlabZgXX where YYYY is current year, Z is the Lab number, and XX is the actual group number (it may start with 0)', max_length=10, unique=True, validators=[delay.models.validate_repo_name]),
        ),
        migrations.AlterField(
            model_name='sogroup',
            name='secret_key',
            field=models.CharField(editable=False, help_text='AutoGenerated unique key for this group. They need to use it to win the challenge', max_length=100),
        ),
        migrations.AlterField(
            model_name='sogroup',
            name='wasted_time',
            field=models.IntegerField(default=0, editable=False, help_text='Total wasted time accumulated in minutes (rounded)'),
        ),
    ]
