# Generated by Django 5.0.7 on 2024-08-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0010_alter_sogroup_options_alter_sogroup_wasted_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pingpong',
            old_name='tampering_attemp',
            new_name='tampering_attempt',
        ),
    ]
