# Generated by Django 5.0.7 on 2024-08-20 02:33

import delay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0011_rename_tampering_attemp_pingpong_tampering_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sogroup',
            name='repo_name',
            field=models.CharField(help_text='The repo name must follow the pattern soYYYYlabZgXX where YYYY is current year, Z is the Lab number, and XX is the actual group number (it may start with 0)', max_length=20, unique=True, validators=[delay.models.validate_repo_name]),
        ),
    ]
